import { z } from "zod"

export const newPropertySchema = z.object({
    id: z.string(),
    source: z.string(),
    name: z.string(),
    address1: z.string(),
    address2: z.string(),
    city: z.string(),
    state: z.string(),
    postalCode: z.string(),
    country: z.string(),
    latitude: z.number().optional(),
    longitude: z.number().optional(),
    stdAddress1: z.string(),
    stdAddress2: z.string(),
    stdCity: z.string(),
    stdState: z.string(),
    stdStateCode: z.string(),
    stdCounty: z.string(),
    stdPostalCode: z.string(),
    stdCountry: z.string(),
    stdCountryCode: z.string(),
    stdLatitude: z.number().optional(),
    stdLongitude: z.number().optional(),
    googleLocationType: z.string(),
    googleAddressType: z.string(),
    stdFullAddress: z.string(),
    propertyType: z.string(),
    propertySubType: z.string().optional(),
    propertyStyle: z.string().optional(),
    buildingClass: z.string().optional(),
    buildingSizeSqFt: z.number().optional(),
    yearBuilt: z.number(),
    numberOfUnits: z.number(),
    beds: z.string().optional(),
    sizeAcres: z.number().optional(),
    createdBy: z.string().optional(),
    lastUpdatedBy: z.string().optional(),
    lastUpdatedDate: z.string().optional(),
    createdDate: z.string().optional()
})

export type NewProperty = z.infer<typeof newPropertySchema>