export interface Property {
    id: string;
    source: string;
    sourceId: string;
    name: string;
    address1: string;
    address2: string;
    city: string;
    state: string;
    postalCode: string;
    country: string;
    latitude: number | null;
    longitude: number | null;
    stdAddress1: string;
    stdAddress2: string;
    stdCity: string;
    stdState: string;
    stdStateCode: string;
    stdCounty: string;
    stdPostalCode: string;
    stdCountry: string;
    stdCountryCode: string;
    stdLatitude: number | null;
    stdLongitude: number | null;
    googleLocationType: string;
    googleAddressType: string;
    profiseeMasterRecordId: string;
    stdFullAddress: string;
    propertyType: string;
    propertySubType: string;
    propertyStyle: string;
    buildingClass: string;
    buildingStatus: string;
    buildingSizeSqFt: number | null;
    yearBuilt: number | null;
    completionDate: string | null;
    rentType: string;
    numberOfUnits: number | null;
    market: string;
    lastSalePrice: number | null;
    crossStreet: string;
    crossStreet2: string;
    county: string;
    borough: string;
    township: string;
    dateRenovated: string;
    siding: string;
    roofing: string;
    beds: string;
    sizeAcres: string;
    stories: string;
    region: string;
    garages: string;
    carports: string;
    buildings: string;
    website: string;
    parcelNumber: string;
    parkingSpaces: string;
    subMarket: string;
    createdBy: string;
    lastUpdatedBy: string;
    lastUpdatedDate: string | null;
    createdDate: string | null;
    mapNumber: string;
    microMarket: string;
    municipality: string;
    configuration: string;
    designation: string;
    intendedUse: string;
    intendedSubUse: string;
    rate: string;
    rateDetail: string;
    composition: string;
    lastReplaced: string;
    sliding: string;
}